/* tslint:disable */
/**
 * This file was automatically generated by Payload CMS.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    media: Media;
    slider: Slider;
    product: Product;
    categories: Category;
    pages: Page;
    variants: Variant;
    shades: Shade;
    users: User;
  };
  globals: {
    offer: Offer;
  };
}
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
  sizes?: {
    card?: {
      url?: string;
      width?: number;
      height?: number;
      mimeType?: string;
      filesize?: number;
      filename?: string;
    };
    feature?: {
      url?: string;
      width?: number;
      height?: number;
      mimeType?: string;
      filesize?: number;
      filename?: string;
    };
  };
}
export interface Slider {
  id: string;
  title: string;
  description: string;
  buttonText: string;
  img: string | Media;
  category: string | Category;
  updatedAt: string;
  createdAt: string;
}
export interface Category {
  id: string;
  category_name?: string;
  updatedAt: string;
  createdAt: string;
}
export interface Product {
  id: string;
  product_name: string;
  price: number;
  quantity: number;
  discount: number;
  description: {
    [k: string]: unknown;
  }[];
  image: {
    image?: string | Media;
    id?: string;
  }[];
  category: string | Category;
  variant: string | Variant;
  shade: string | Shade;
  updatedAt: string;
  createdAt: string;
}
export interface Variant {
  id: string;
  color?: string;
  updatedAt: string;
  createdAt: string;
}
export interface Shade {
  id: string;
  shade?: string;
  updatedAt: string;
  createdAt: string;
}
export interface Page {
  id: string;
  title: string;
  image?: string | Media;
  layout?: (
    | {
        content?: {
          [k: string]: unknown;
        }[];
        buttons: {
          label: string;
          type: 'page' | 'custom';
          page: string | Page;
          url: string;
          newTab: boolean;
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'cta';
      }
    | {
        content?: {
          [k: string]: unknown;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'content';
      }
    | {
        image: string | Media;
        type?: 'normal' | 'fullscreen' | 'wide';
        caption?: {
          [k: string]: unknown;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'image';
      }
  )[];
  meta?: {
    title?: string;
    description?: string;
    keywords?: string;
  };
  slug?: string;
  updatedAt: string;
  createdAt: string;
}
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email?: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  loginAttempts?: number;
  lockUntil?: string;
  password?: string;
}
export interface Offer {
  id: string;
  title: string;
  description: string;
  color: string;
  link: string;
  linkText: string;
  image: string | Media;
}
