/* tslint:disable */
/**
 * This file was automatically generated by Payload CMS.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    sales: Sale;
    media: Media;
    slider: Slider;
    product: Product;
    categories: Category;
    customer: Customer;
    variants: Variant;
    shades: Shade;
    users: User;
  };
  globals: {
    social: Social;
    offer: Offer;
  };
}
export interface Sale {
  id: string;
  customer: string | Customer;
  gross_sale: number;
  net_sale: number;
  discount: number;
  products_sales: {
    product?: string | Product;
    id?: string;
  }[];
  updatedAt: string;
  createdAt: string;
}
export interface Customer {
  id: string;
  customer_name: string;
  email?: string;
  phone: string;
  updatedAt: string;
  createdAt: string;
}
export interface Product {
  id: string;
  product_name: string;
  price: number;
  quantity: number;
  discount: number;
  description: {
    [k: string]: unknown;
  }[];
  image: {
    image?: Media;
    id?: string;
  }[];
  category: Category;
  variant: Variant;
  shade:  Shade;
  updatedAt: string;
  createdAt: string;
}
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
  sizes?: {
    card?: {
      url?: string;
      width?: number;
      height?: number;
      mimeType?: string;
      filesize?: number;
      filename?: string;
    };
    feature?: {
      url?: string;
      width?: number;
      height?: number;
      mimeType?: string;
      filesize?: number;
      filename?: string;
    };
  };
}
export interface Category {
  id: string;
  category_name?: string;
  updatedAt: string;
  createdAt: string;
}
export interface Variant {
  id: string;
  color?: string;
  updatedAt: string;
  createdAt: string;
}
export interface Shade {
  id: string;
  shade?: string;
  updatedAt: string;
  createdAt: string;
}
export interface Slider {
  id: string;
  title: string;
  description: string;
  buttonText: string;
  img: string | Media;
  category: string | Category;
  updatedAt: string;
  createdAt: string;
}
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email?: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  loginAttempts?: number;
  lockUntil?: string;
  password?: string;
}
export interface Social {
  id: string;
  facebook: string;
  instagram: string;
  whatsapp: string;
  phone: string;
  email: string;
  address: string;
}
export interface Offer {
  id: string;
  title: string;
  description: string;
  color: string;
  link: string;
  linkText: string;
  image: string | Media;
}
